; Generated by Installer.Cli. Per-user install: no administrator rights, nothing outside the user's profile.
Unicode true
ManifestDPIAware true
RequestExecutionLevel user
SetCompressor /SOLID lzma
!include "MUI2.nsh"

Name "ScreenRec"
OutFile "/w/ScreenRec-1.0.0-b12-windows-x64-setup.exe"
InstallDir "$LOCALAPPDATA\Programs\ScreenRec"
BrandingText "ScreenRec 1.0.0-b12"
!define UNINSTALL_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\dev.screenrec.app"
!define MUI_ICON "/w/app.ico"
!define MUI_UNICON "/w/app.ico"
!define MUI_FINISHPAGE_RUN "$INSTDIR\ScreenRec.exe"

!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

VIProductVersion "1.0.0.12"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "ScreenRec"
VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "Ward Yorgason"
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "Screen recorder"
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileVersion" "1.0.0.12"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductVersion" "1.0.0-b12"

Section "Install"
  SetShellVarContext current
  ; Upgrade in place: remove the previous installation with its own uninstaller, so files the new
  ; version no longer ships do not remain.
  ReadRegStr $0 HKCU "${UNINSTALL_KEY}" "InstallLocation"
  StrCmp $0 "" install
  IfFileExists "$0\uninstall.exe" 0 install
  ExecWait '"$0\uninstall.exe" /S _?=$0'
  Delete "$0\uninstall.exe"
  RMDir "$0"
install:
  SetOutPath "$INSTDIR"
  File /r "/w/payload/*"
  WriteUninstaller "$INSTDIR\uninstall.exe"
  CreateShortcut "$SMPROGRAMS\ScreenRec.lnk" "$INSTDIR\ScreenRec.exe"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayName" "ScreenRec"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayVersion" "1.0.0-b12"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "Publisher" "Ward Yorgason"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayIcon" "$INSTDIR\ScreenRec.exe"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr HKCU "${UNINSTALL_KEY}" "QuietUninstallString" '"$INSTDIR\uninstall.exe" /S'
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "NoRepair" 1
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "EstimatedSize" 2048
SectionEnd

Section "Uninstall"
  SetShellVarContext current
  Delete "$SMPROGRAMS\ScreenRec.lnk"
  RMDir /r "$INSTDIR"
  DeleteRegKey HKCU "${UNINSTALL_KEY}"
SectionEnd
