using System.Globalization;
using System.Text;

namespace Installer.Services.Windows;

internal sealed class NsisScriptService : INsisScriptService
{
    public string Generate(NsisScriptRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        var exe = "$INSTDIR\\" + Escape(request.MainExecutable.Replace('/', '\\'));
        var key = @"Software\Microsoft\Windows\CurrentVersion\Uninstall\" + request.Id;
        var script = new StringBuilder();
        void Line(string text = "") => script.Append(text).Append('\n');

        Line("; Generated by Installer.Cli. Per-user install: no administrator rights, nothing outside the user's profile.");
        Line("Unicode true");
        Line("ManifestDPIAware true");
        Line("RequestExecutionLevel user");
        Line("SetCompressor /SOLID lzma");
        Line("!include \"MUI2.nsh\"");
        Line();
        Line($"Name {Quote(request.Name)}");
        Line($"OutFile {Quote(request.OutputFile)}");
        Line($"InstallDir {Quote("$LOCALAPPDATA\\Programs\\" + Escape(request.Name), escape: false)}");
        Line($"BrandingText {Quote($"{request.Name} {request.DisplayVersion}")}");
        Line($"!define UNINSTALL_KEY {Quote(key)}");
        Line($"!define MUI_ICON {Quote(request.IconPath)}");
        Line($"!define MUI_UNICON {Quote(request.IconPath)}");
        Line($"!define MUI_FINISHPAGE_RUN {Quote(exe, escape: false)}");
        Line();
        Line("!insertmacro MUI_PAGE_INSTFILES");
        Line("!insertmacro MUI_PAGE_FINISH");
        Line("!insertmacro MUI_UNPAGE_CONFIRM");
        Line("!insertmacro MUI_UNPAGE_INSTFILES");
        Line("!insertmacro MUI_LANGUAGE \"English\"");
        Line();
        Line($"VIProductVersion {Quote(request.FourPartVersion)}");
        Line($"VIAddVersionKey /LANG=${{LANG_ENGLISH}} \"ProductName\" {VersionInfo(request.Name)}");
        Line($"VIAddVersionKey /LANG=${{LANG_ENGLISH}} \"CompanyName\" {VersionInfo(request.Publisher)}");
        Line($"VIAddVersionKey /LANG=${{LANG_ENGLISH}} \"FileDescription\" {VersionInfo(request.Description)}");
        Line($"VIAddVersionKey /LANG=${{LANG_ENGLISH}} \"FileVersion\" {VersionInfo(request.FourPartVersion)}");
        Line($"VIAddVersionKey /LANG=${{LANG_ENGLISH}} \"ProductVersion\" {VersionInfo(request.DisplayVersion)}");
        if (request.SignHook is not null)
        {
            Line();
            Line("; Authenticode hook: sign the uninstaller before it is embedded, and the finished setup executable.");
            Line($"!uninstfinalize {SingleQuote(request.SignHook)}");
            Line($"!finalize {SingleQuote(request.SignHook)}");
        }

        Line();
        Line("Section \"Install\"");
        Line("  SetShellVarContext current");
        Line("  ; Upgrade in place: remove the previous installation with its own uninstaller, so files the new");
        Line("  ; version no longer ships do not remain.");
        Line("  ReadRegStr $0 HKCU \"${UNINSTALL_KEY}\" \"InstallLocation\"");
        Line("  StrCmp $0 \"\" install");
        Line("  IfFileExists \"$0\\uninstall.exe\" 0 install");
        Line("  ExecWait '\"$0\\uninstall.exe\" /S _?=$0'");
        Line("  Delete \"$0\\uninstall.exe\"");
        Line("  RMDir \"$0\"");
        Line("install:");
        Line("  SetOutPath \"$INSTDIR\"");
        Line($"  File /r {Quote(Path.Combine(request.PayloadDirectory, "*"))}");
        Line("  WriteUninstaller \"$INSTDIR\\uninstall.exe\"");
        Line($"  CreateShortcut {Quote("$SMPROGRAMS\\" + Escape(request.Name) + ".lnk", escape: false)} {Quote(exe, escape: false)}");
        Line($"  WriteRegStr HKCU \"${{UNINSTALL_KEY}}\" \"DisplayName\" {Quote(request.Name)}");
        Line($"  WriteRegStr HKCU \"${{UNINSTALL_KEY}}\" \"DisplayVersion\" {Quote(request.DisplayVersion)}");
        Line($"  WriteRegStr HKCU \"${{UNINSTALL_KEY}}\" \"Publisher\" {Quote(request.Publisher)}");
        Line($"  WriteRegStr HKCU \"${{UNINSTALL_KEY}}\" \"DisplayIcon\" {Quote(exe, escape: false)}");
        Line("  WriteRegStr HKCU \"${UNINSTALL_KEY}\" \"InstallLocation\" \"$INSTDIR\"");
        Line("  WriteRegStr HKCU \"${UNINSTALL_KEY}\" \"UninstallString\" '\"$INSTDIR\\uninstall.exe\"'");
        Line("  WriteRegStr HKCU \"${UNINSTALL_KEY}\" \"QuietUninstallString\" '\"$INSTDIR\\uninstall.exe\" /S'");
        Line("  WriteRegDWORD HKCU \"${UNINSTALL_KEY}\" \"NoModify\" 1");
        Line("  WriteRegDWORD HKCU \"${UNINSTALL_KEY}\" \"NoRepair\" 1");
        Line($"  WriteRegDWORD HKCU \"${{UNINSTALL_KEY}}\" \"EstimatedSize\" {request.EstimatedSizeKb.ToString(CultureInfo.InvariantCulture)}");
        Line("SectionEnd");
        Line();
        Line("Section \"Uninstall\"");
        Line("  SetShellVarContext current");
        Line($"  Delete {Quote("$SMPROGRAMS\\" + Escape(request.Name) + ".lnk", escape: false)}");
        Line("  RMDir /r \"$INSTDIR\"");
        Line("  DeleteRegKey HKCU \"${UNINSTALL_KEY}\"");
        Line("SectionEnd");
        return script.ToString();
    }

    public string SignHook(IReadOnlyList<string> selfInvocation, string commandJsonPath)
    {
        ArgumentNullException.ThrowIfNull(selfInvocation);
        var parts = selfInvocation.Select(ShellQuote)
            .Concat(["sign-file", "\"%1\"", "--command-json", ShellQuote(commandJsonPath)]);
        return string.Join(' ', parts);
    }

    /// <summary>NSIS escapes: <c>$</c> starts a variable and <c>"</c> ends the string.</summary>
    private static string Escape(string text) => text.Replace("$", "$$", StringComparison.Ordinal).Replace("\"", "$\\\"", StringComparison.Ordinal);

    /// <summary>Version-information values are stored as written: only the quote needs escaping, a doubled $ would stay doubled.</summary>
    private static string VersionInfo(string text) => "\"" + text.Replace("\"", "$\\\"", StringComparison.Ordinal) + "\"";

    private static string Quote(string text, bool escape = true) => "\"" + (escape ? Escape(text) : text) + "\"";

    /// <summary>A single-quoted NSIS string, so the shell command inside can use double quotes.</summary>
    private static string SingleQuote(string text) => "'" + text.Replace("$", "$$", StringComparison.Ordinal) + "'";

    private static string ShellQuote(string argument) => "\"" + argument.Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
}
